services:
  service:
    container_name: service
    build:
      context: .
      dockerfile: ./apps/service/Dockerfile
    networks:
      - public
    ports:
      - "3000:3000"
    volumes:
      - storage:/app/data
    restart: always
    develop:
      watch:
        - action: sync
          path: ./apps/service
          target: ./app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json

volumes:
  storage:

networks:
  public:
