#!/bin/sh
# vaze installer — fetches compose.prod.yaml, generates secrets into .env, starts the container.
#   curl -fsSL https://raw.githubusercontent.com/darseen/vaze/main/scripts/install.sh | sh
# Re-run it in an existing install to upgrade: your data, secrets and edits are preserved.
set -eu

REPO=${VAZE_REPO:-darseen/vaze}
REF=${VAZE_REF:-main}
RAW=${VAZE_RAW:-https://raw.githubusercontent.com/$REPO/$REF}
START=1

# VAZE_REF=2.2.0 should pin the image too, not just the compose file.
case "$REF" in
  [0-9]*.[0-9]*) VAZE_VERSION=${VAZE_VERSION:-$REF} ;;
esac

for arg in "$@"; do
  case "$arg" in
    --no-start) START=0 ;;
    --dir=*) VAZE_DIR=${arg#--dir=} ;;
    -h | --help)
      echo "usage: install.sh [--dir=PATH] [--no-start]"
      echo "env: BASE_URL, VAZE_DIR, VAZE_PORT, VAZE_VERSION, VAZE_REF, VAZE_REPO"
      exit 0
      ;;
    *)
      echo "unknown option: $arg" >&2
      exit 2
      ;;
  esac
done

info() { printf '\033[36m[vaze]\033[0m %s\n' "$1"; }
warn() { printf '\033[33m[vaze]\033[0m %s\n' "$1" >&2; }
die() {
  printf '\033[31m[vaze]\033[0m %s\n' "$1" >&2
  exit 1
}

need() { command -v "$1" >/dev/null 2>&1; }

fetch() {
  if need curl; then
    curl -fsSL "$1"
  elif need wget; then
    wget -qO- "$1"
  else die "need curl or wget to download files"; fi
}

rand_b64() {
  if need openssl; then
    openssl rand -base64 32
  else head -c 32 /dev/urandom | base64; fi | tr -d '\n'
}

# -r /dev/tty is not enough: it exists but fails to open with no controlling
# terminal. Subshell so that failure is a status, not a fatal redirect error.
has_tty() { (: >/dev/tty) 2>/dev/null; }

ask() {
  _q=$1 _default=$2 _answer=""
  if has_tty; then
    printf '\033[36m[vaze]\033[0m %s [%s]: ' "$_q" "$_default" >/dev/tty
    read -r _answer </dev/tty || _answer=""
  fi
  [ -n "$_answer" ] || _answer=$_default
  printf '%s' "$_answer"
}

env_get() {
  [ -f .env ] || return 0
  sed -n "s/^[[:space:]]*$1=//p" .env | head -n1
}

env_put() {
  if [ -n "$(env_get "$1")" ]; then return 0; fi
  printf '%s=%s\n' "$1" "$2" >>.env
}

is_ipv4() { printf '%s' "${1:-}" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; }

# The address other machines reach this host on — a better default than
# localhost for a file server that hands out shareable URLs.
lan_addr() {
  _ip=""
  if need ip; then
    _ip=$(ip -4 route get 1.1.1.1 2>/dev/null |
      awk '{for (i = 1; i < NF; i++) if ($i == "src") print $(i + 1); exit}')
    is_ipv4 "$_ip" || _ip=""
  fi
  if [ -z "$_ip" ]; then
    _ip=$(hostname -I 2>/dev/null | awk '{print $1}')
    is_ipv4 "$_ip" || _ip=""
  fi
  if [ -n "$_ip" ]; then printf '%s' "$_ip"; else printf 'localhost'; fi
}

need docker || die "docker is not installed — see https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "the docker compose plugin is required (docker compose version)"
docker info >/dev/null 2>&1 || die "cannot reach the docker daemon — is it running, and is your user in the docker group?"

if [ -z "${VAZE_DIR:-}" ]; then
  if [ -f .env ] && [ -f compose.prod.yaml ]; then VAZE_DIR=$PWD; else VAZE_DIR=$PWD/vaze; fi
fi
mkdir -p "$VAZE_DIR"
cd "$VAZE_DIR"

if [ -f .env ]; then
  info "existing install found in $VAZE_DIR — keeping .env and your data, updating compose.prod.yaml"
else
  info "installing into $VAZE_DIR"
fi

info "fetching compose.prod.yaml"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT INT TERM
fetch "$RAW/compose.prod.yaml" >"$tmp" || die "could not download compose.prod.yaml from $RAW"
[ -s "$tmp" ] || die "downloaded compose.prod.yaml is empty"
if [ -f compose.prod.yaml ] && ! cmp -s "$tmp" compose.prod.yaml; then
  cp compose.prod.yaml compose.prod.yaml.bak
  info "previous compose.prod.yaml saved as compose.prod.yaml.bak"
fi
cat "$tmp" >compose.prod.yaml

port=${VAZE_PORT:-$(env_get VAZE_PORT)}
[ -n "$port" ] || port=3000

base_url=${BASE_URL:-$(env_get BASE_URL)}
if [ -z "$base_url" ]; then
  base_url=$(ask "URL you will open vaze on" "http://$(lan_addr):$port")
  has_tty || warn "no terminal to prompt on — defaulting BASE_URL to $base_url; edit .env if that is not the URL you open"
fi

if [ ! -f .env ]; then
  umask 077
  cat >.env <<EOF
# Generated by scripts/install.sh. Keep AUTH_SECRET backed up: replacing it
# signs everyone out. Uploaded files live in the vaze_vaze_data docker volume.

VAZE_VERSION=${VAZE_VERSION:-latest}

AUTH_SECRET=$(rand_b64)

# The URL you open vaze on. Public file links are built from it, so keep it in
# sync with your domain or reverse proxy.
BASE_URL=$base_url

# Set VAZE_BIND_ADDR=127.0.0.1 when a reverse proxy fronts vaze.
VAZE_BIND_ADDR=${VAZE_BIND_ADDR:-0.0.0.0}
VAZE_PORT=$port

TZ=${TZ:-UTC}
EOF
  info "wrote .env with a freshly generated AUTH_SECRET"
else
  # Only fill gaps — never touch a value the user already has.
  env_put VAZE_VERSION "${VAZE_VERSION:-latest}"
  env_put AUTH_SECRET "$(rand_b64)"
  env_put BASE_URL "$base_url"
  env_put VAZE_BIND_ADDR "${VAZE_BIND_ADDR:-0.0.0.0}"
  env_put VAZE_PORT "$port"
  env_put TZ "${TZ:-UTC}"
fi
chmod 600 .env 2>/dev/null || true

if [ "$START" -eq 0 ]; then
  info "skipping start — run: docker compose -f compose.prod.yaml up -d"
  exit 0
fi

info "pulling image"
docker compose -f compose.prod.yaml pull --quiet

info "starting vaze"
docker compose -f compose.prod.yaml up -d --remove-orphans

port=$(env_get VAZE_PORT)
[ -n "$port" ] || port=3000
url=$(env_get BASE_URL)

info "waiting for vaze to become healthy (migrations run on first boot)"
i=0
while [ "$i" -lt 60 ]; do
  state=$(docker compose -f compose.prod.yaml ps --format '{{.Health}}' vaze 2>/dev/null || true)
  case "$state" in
    healthy) break ;;
    unhealthy) die "vaze is unhealthy — docker compose -f compose.prod.yaml logs vaze" ;;
  esac
  i=$((i + 1))
  sleep 2
done

if [ "$i" -ge 60 ]; then
  warn "vaze did not report healthy in time — check: docker compose -f compose.prod.yaml logs -f vaze"
else
  info "vaze is up"
fi

echo
info "open $url and register — the first account becomes the admin"
info "listening on port $port  ·  files in $VAZE_DIR  ·  secrets in $VAZE_DIR/.env"
info "re-run this installer from $VAZE_DIR to upgrade — your uploads and .env are kept"
