name: Docker Image CI

on: { workflow_dispatch }

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -f ./apps/service/Dockerfile -t darsee/vaze:latest .

      - name: Push image
        run: |
          docker push darsee/vaze:latest
